name: Build macOS App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build DMG
        # Use 'packageReleaseDmg' if you have a release build type configured
        run: ./gradlew packageDmg 
        
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Installer
          path: composeApp/build/compose/binaries/main/dmg/*.dmg
